# Numpy Basics
NumPy is the fundamental package for scientific computing in Python.

It’s a Python library that provides
- multidimensional array object 
- various derived objects (such as masked arrays and matrices) 
- an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
import numpy as np

## 1. np.array - ndarray
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the
same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called *axes*.

### 1.1 Basic Features

In [2]:
a = np.arange(15).reshape(3,5)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a)

<class 'numpy.ndarray'>
2
(3, 5)
15
int32
4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### 1.2 Array Creation

a) Create an array from a regular Python **list** or **tuple** using the array function. (accept sigle argument, type remains)

In [3]:
a = np.array([1,2,3],dtype=complex)
print(a)
print(a.dtype)
b = np.array([(1.1,2.2,3.3),(4,5,6)])
print(b)
print(b.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128
[[1.1 2.2 3.3]
 [4.  5.  6. ]]
float64


b) Create arrays with initial placeholder content (dtype=float64 as default)

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
np.empty([2,4])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.53353523e-321, 1.24610723e-306,
        1.29061142e-306]])

c) Create sequences of numbers

In [7]:
np.arange(10,35,5) # stop number excluded

array([10, 15, 20, 25, 30])

In [8]:
np.linspace(0,9,10) # stop number included

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 1.3 Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [9]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### 1.4 Basic Operations

In [10]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [11]:
print(a - b)

[20 29 38 47]


In [12]:
print(b * 2)

[0 2 4 6]


In [13]:
print(a < 35)

[ True  True False False]


In [14]:
A = np.array(((1,2),(3,4)))
B = np.array(((2,1),(4,3)))
# elementwise product
print(A * B)
# matrix product
print(A @ B)
# dot matrix product
print(A.dot(B))

[[ 2  2]
 [12 12]]
[[10  7]
 [22 15]]
[[10  7]
 [22 15]]


In [15]:
print(A.sum())
print(A.min())
print(A.max())

10
1
4


In [16]:
print(B.sum(axis=0))
print(B.sum(axis=1))
print(B.max(axis=1))

[6 4]
[3 7]
[2 4]


In [17]:
print(np.exp(A))
print(np.sqrt(B))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[1.41421356 1.        ]
 [2.         1.73205081]]


### 1.5 Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas.

The dots (...) represent as many colons as needed to produce a complete indexing tuple

- x[1, 2, ...] is equivalent to x[1, 2, :, :, :],
- x[..., 3] to x[:, :, :, :, 3] and
- x[4, ..., 5, :] to x[4, :, :, 5, :]

In [18]:
def f(x,y):
    return 10 * x + y
b = np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[2,3])
print(b[0:4,1]) # 4 is excluded
print(b[1:3,])
print(b[-1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


Indexing with Arrays of Indices

In [19]:
a = np.arange(12) ** 2
print(a)
print(a[np.array([1,1,8,3,5])])
print(a[np.array([[3,4],[5,6]])])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1 64  9 25]
[[ 9 16]
 [25 36]]


In [20]:
palette = np.array([
    [0, 0, 0], # black
    [255, 255, 255], # white
    [255, 0, 0], # red
    [0, 255, 0], # green
    [0, 0, 255], # blue
])
image = np.array([
    [1,4,1],
    [0,3,2]
])
print(palette[image])


[[[255 255 255]
  [  0   0 255]
  [255 255 255]]

 [[  0   0   0]
  [  0 255   0]
  [255   0   0]]]


In [21]:
# indices for more than one dimension
a = np.arange(12).reshape(3,4)
print(a)
i = np.array([
    [0,1],
    [1,2]
])
j = np.array([
    [2,1],
    [3,3]
])
print(a[i,j]) # can also be a[(i,j)] but not a[[i,j]](be indexing the first dimension)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  5]
 [ 7 11]]


Indexing with Boolean Arrays

In [22]:
# The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape 
# as the original array:
a = np.arange(12).reshape(3, 4)
b = a > 4
print(a)
print(a[b]) # get the selected items

# The second way of indexing with booleans is more similar to integer indexing; for each dimension of the array 
# we give a 1D boolean array selecting the slices we want
b1 = np.array([False, True, True])
b2 = np.array([True, False, True, False])
print(a[b1,:]) # selecting axis 0
print(a[:,b2]) # selecting axis 1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 5  6  7  8  9 10 11]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


The ix_() function

The ix_ function can be used to combine different vectors so as to obtain the result for each n-uplet. For example, if you want to compute all the a+b*c for all the triplets taken from each of the vectors a, b and c:

In [23]:
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])
ax, bx, cx = np.ix_(a, b, c)
print(ax)
print(bx)
print(cx)
result = ax + bx * cx
print(result)

[[[2]]

 [[3]]

 [[4]]

 [[5]]]
[[[8]
  [5]
  [4]]]
[[[5 4 6 8 3]]]
[[[42 34 50 66 26]
  [27 22 32 42 17]
  [22 18 26 34 14]]

 [[43 35 51 67 27]
  [28 23 33 43 18]
  [23 19 27 35 15]]

 [[44 36 52 68 28]
  [29 24 34 44 19]
  [24 20 28 36 16]]

 [[45 37 53 69 29]
  [30 25 35 45 20]
  [25 21 29 37 17]]]


Iterating

In [24]:
for row in b:
    print(row)

8
5
4


In [25]:
for element in b.flat:
    print(element)

8
5
4


### 1.6 Shape Manipulation

Changing the shape of an array.

In [26]:
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3,4)))
print(a)
print(a.shape)

[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
(3, 4)


In [27]:
# the original a will not be changed
print(a.ravel())
print(a.reshape((4,3)))
print(a.reshape(3,-1)) # If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
print(a.T)

[5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]
[[5. 9. 1.]
 [9. 3. 4.]
 [8. 4. 5.]
 [0. 7. 5.]]
[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
[[5. 3. 5.]
 [9. 4. 0.]
 [1. 8. 7.]
 [9. 4. 5.]]


In [28]:
# the original a will be changed (return None)
a.resize((4,3))
print(a)

[[5. 9. 1.]
 [9. 3. 4.]
 [8. 4. 5.]
 [0. 7. 5.]]


Stacking together different arrays

In [29]:
a = np.floor(10 * rg.random((2,2)))
b = np.floor(10 * rg.random((2,2)))
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[3. 7.]
 [3. 4.]]
[[1. 4.]
 [2. 2.]]
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]]
[[3. 7. 1. 4.]
 [3. 4. 2. 2.]]


Splitting one array into several smaller ones.

In [30]:
a = np.floor(10 * rg.random((2,12)))
print(a)
print(np.hsplit(a,3)) # Split a into 3
print(np.hsplit(a,(3,4))) # Split a after the third and the fourth column

[[7. 2. 4. 9. 9. 7. 5. 2. 1. 9. 5. 1.]
 [6. 7. 6. 9. 0. 5. 4. 0. 6. 8. 5. 2.]]
[array([[7., 2., 4., 9.],
       [6., 7., 6., 9.]]), array([[9., 7., 5., 2.],
       [0., 5., 4., 0.]]), array([[1., 9., 5., 1.],
       [6., 8., 5., 2.]])]
[array([[7., 2., 4.],
       [6., 7., 6.]]), array([[9.],
       [9.]]), array([[9., 7., 5., 2., 1., 9., 5., 1.],
       [0., 5., 4., 0., 6., 8., 5., 2.]])]


In [31]:
a = np.floor(10 * rg.random((2,3,4)))
print(a)
# numpy.array_split(ary, indices_or_sections, axis=0)
print(np.array_split(a,(1,),axis=1))

[[[8. 5. 5. 7.]
  [1. 8. 6. 7.]
  [1. 8. 1. 0.]]

 [[8. 8. 8. 4.]
  [2. 0. 6. 7.]
  [8. 2. 2. 6.]]]
[array([[[8., 5., 5., 7.]],

       [[8., 8., 8., 4.]]]), array([[[1., 8., 6., 7.],
        [1., 8., 1., 0.]],

       [[2., 0., 6., 7.],
        [8., 2., 2., 6.]]])]


Copies and views.
- The view method creates a new array object that looks at the same data.
- The copy method makes a complete copy of the array and its data.

In [32]:
a = np.floor(10 * rg.random((3,4)))
print(a)
c = a.view()
print(c is a)
print(c.base is a)
print(c.flags.owndata)
c = c.reshape((4,3)) # a does not change
c[1,2] = 123 # a changes
print(a)

[[8. 9. 1. 4.]
 [8. 4. 5. 0.]
 [6. 9. 8. 8.]]
False
True
False
[[  8.   9.   1.   4.]
 [  8. 123.   5.   0.]
 [  6.   9.   8.   8.]]


In [33]:
d = a.copy()
print(d is a)
print(d.base is a)
print(d.flags.owndata)
# a will not change no matter how d changes

False
False
True


### 1.3.1.7 Functions and Methods Overview

| Purposes | Functions |
| --- | --- |
| Array Creation | arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like |
| Conversions | ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat |
| Manipulations | array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack |
| Questions | all, any, nonzero, where |
| Ordering | argmax, argmin, argsort, max, min, ptp, searchsorted, sort |
| Operations | choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum |
| Basic Statistics | cov, mean, std, var |
| Basic Linear Algebra | cross, dot, outer, linalg.svd, vdot |

In [34]:
a = np.arange(24).reshape(2,3,4)
print(a)
print(np.argmax(a,axis=0)) # along the axis 0 - same axis 1&2 index - shape=(shape[1],shape[2])
print(np.argmax(a,axis=1)) # along the axis 1 - same axis 0&2 index
print(np.argmax(a,axis=2)) # along the axis 2 - same axis 0&1 index

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2 2 2 2]
 [2 2 2 2]]
[[3 3 3]
 [3 3 3]]
